#!/bin/bash
# UKMac <===> Ubuntu Key Maker for MAC
# Version 1.5
# Author : Adonis NAJIMI (FR) 
# Github : @Adopi
# You can do anything with this script.
# But if you want to use my work you have to quote me

if [[ $EUID -ne 0 ]]
	then
	echo "This script must be run as root"
	exit 777
fi

#iso path
path_iso=$1

#choose file if path_iso doesn't exist
while  ! [ -f $path_iso  ]
do
	read -p "Iso file:" path_iso
done

echo " ### Ubuntu Key Maker ### "
echo "File: $path_iso"
read -p "Press a key to continue" key
#convert file
hdiutil convert -format UDRW -o /tmp/target.img $path_iso 2> /dev/null

echo "Where do you want to install the distribution?"

list=$(diskutil list | grep '/')
for disk_path in $list
do
	echo $disk_path
done
#choose disk
read -p ": disk" disk
disk='disk'$disk

check_disk=0
list=$(echo $list | sed 's/\/dev\///g')

#check disk
for i in $list 
do
	if [ $i = $disk ] 
		then
		check_disk=1
	fi
done



disk_path="/dev/"$disk
echo "$disk selected"
read -p "Press a key to finish the installation on $disk" key
#mv img file into disk selected
if [ $check_disk -eq 1 ]
	then
	#umount all partitions of this disk
	diskutil unmountDisk $disk
echo "All partitions are unmouted"
	dd if=/tmp/target.img.dmg of=$disk_path bs=1m
else
	echo "$disk_path doesn't exist"
	exit 121
fi



rm -rf /tmp/target.img.dmg

echo "END!"
echo "Don't forget to eject your disk drive!"

exit 0

#END UKMac
