#!/bin/bash
# UKMac <===> Ubuntu Key Maker for MAC
# Version 1.0
# Author : Adonis NAJIMI (FR) 
# Github : @Adopi
# You can do anything with this script.
# But if you want to use my work you have to quote me


#iso path
path_iso=$1

#choose file if path_iso doesn't exist
while  ! [ -f $path_iso  ]
do
	read -p "Iso file:" path_iso
done

echo " ### Ubuntu Key Maker ### "
echo "File: $path_iso"
echo "press a key to continue"
#convert file
hdiutil convert -format UDRW -o /tmp/target.img $path_iso

echo "Where do you want to install the distribution?"

list=$(diskutil list | grep '/')
for disk_path in $list
do
	echo $disk_path
done
#choose disk
read -p ": disk" disk
disk='disk'$disk

check_disk=0
list=$(echo $list | sed 's/\/dev\///g')

#check disk
for i in $list 
do
	if [ $i = $disk ] 
		then
		check_disk=1
	fi
done

disk="/dev/"$disk
echo "$disk selected"
#mv img file into disk selected
if [ $check_disk -eq 1 ]
	then
	echo "To continue you have to enter your password"
	sudo dd if=/tmp/target.img of=$disk bs=1m
else
	echo "$disk doesn't exist"
	exit 121
fi
echo "END!"
echo "Don't forget to eject your disk drive!"

exit 0
#END UKMac
